INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'Every item is thoroughly cleaned and sanitized between events: linens are freshly laundered, mattresses and cushions are wiped down and deodorized, and tents are fully disinfected. Everything arrives fresh and ready for your celebration.', 4 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'Every item is thoroughly cleaned and sanitized between events: linens are freshly laundered, mattresses and cushions are wiped down and deodorized, and tents are fully disinfected. Everything arrives fresh and ready for your celebration.', 4 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'Every item is thoroughly cleaned and sanitized between events: linens are freshly laundered, mattresses and cushions are wiped down and deodorized, and tents are fully disinfected. Everything arrives fresh and ready for your celebration.', 4 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 1 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 2 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'Every item is thoroughly cleaned and sanitized between events: linens are freshly laundered, mattresses and cushions are wiped down and deodorized, and tents are fully disinfected. Everything arrives fresh and ready for your celebration.', 3 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not serve public parks or beaches at this time.
If you are looking to hold an event at a beach or park please check out our DIY Picnic Package.', 0 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not serve public parks or beaches at this time.
If you are looking to hold an event at a beach or park please check out our DIY Picnic Package.', 0 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 3 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 4 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not serve public parks or beaches at this time.
If you are looking to hold an event at a beach or park please check out our DIY Picnic Package.', 0 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 3 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 4 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'The amount of space needed varies by package. Please see below for dimensions for each package:
Indoor Sleepovers and Lounges
Tent Sleepover- Each A-Frame Tent set up requires approximately a 3ft by 6ft space
Lace Teepee Sleepover- Each Teepee set up requires approximately a 3.5ft by 6.5ft space
Outdoor Sleepovers and Lounges
Standard MEGALounge & MEGA GlampOut- 5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
Deluxe MEGALounge & MEGA GlampOut- 6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.
Dining
Celebrations Picnics- We recommend a 8ft x 10ft space for a table of 8. Please contact us for exact dimensions for larger parties.
Farm Table Dining- Each Farm Table is 8ft x 3ft.
Dining in the Tent- 5M MEGATent requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter); 6M MEGATent requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)', 0 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 0 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. We base our schedule on your event start/end time provided at time of booking, location, package, etc.
Deliveries: Deliveries will begin at 8:00am for outdoor events and 9:00am for indoor events and go throughout the day. All sleepover packages will be set up by 4:00pm. Some deliveries may take place the day prior to your event depending on the schedule for that particular date.
Pick Ups: All Sleepover Packages- Pick ups will begin at 10:00am the next day and go throughout the day. All MEGATent Packages- Pick ups will begin at 8:00am the next day and go throughout the day. Picnic Packages- pick up scheduling depends on guest counts, package type, location, weather and other scheduled events. Guaranteed specific delivery/pick up times may incur additional fees and must be requested via email no later than 2 weeks before your event.', 1 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you need access to power?', 'Yes, access to power is needed to run the projector. We will provide ample extension cords.', 2 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you provide the movie?', 'While we do not provide the movie we will provide either a DVD/Blue Ray Player or FireStick. You are responsible for providing a DVD/Blue Ray or for streaming a movie through your own account (Netflix, Hulu, etc.). Please note that if you plan to stream a movie there must be a strong internet signal (wifi or data) available at the movie site.', 3 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you stay for the event?', 'We do not stay for the event. We set up everything you need, leave you to enjoy your event and return the next day (or later that day upon request).', 4 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you stay for the event?', 'We do not stay for the event. We set up everything you need, leave you to enjoy your event and return the next day (or later that day upon request).', 0 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What do guests get to keep?', 'Each guest gets to keep their Spa Slippers, Spa Headband, Applicator Brush, and Facial Products (face wipes, face mask, lotion) and Mani/Pedi Products (bath bomb, toe separators, nail file, nail brush). Robes are for event use only, but personalized satin robes can be added as an option for guests to keep.', 1 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'Every item is thoroughly cleaned and sanitized between events: linens are freshly laundered, mattresses and cushions are wiped down and deodorized, and tents are fully disinfected. Everything arrives fresh and ready for your celebration.', 3 FROM packages WHERE slug = 'pamper-party';
