INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'Each A-Frame Tent set up requires approximately a 3ft by 6ft space. If you are unsure if you have enough space you can provide us with measurements and pictures of the set up area and we can help determine the best layout.', 0 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for indoor sleepover will take place between the hours of 9:00am-4:00pm. Pick ups for all sleepover packages will begin at 10:00am the next day.', 3 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'All hard surfaces are thoroughly disinfected with CDC approved cleaning agents after each use and all linens are professionally laundered.', 4 FROM packages WHERE slug = 'tent-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'Each Lace Teepee set up requires approximately a 3.5ft by 6.5ft space. If you are unsure if you have enough space you can provide us with measurements and pictures of the set up area and we can help determine the best layout.', 0 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for indoor sleepover will take place between the hours of 9:00am-4:00pm. Pick ups for all sleepover packages will begin at 10:00am the next day.', 3 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'All hard surfaces are thoroughly disinfected with CDC approved cleaning agents after each use and all linens are professionally laundered.', 4 FROM packages WHERE slug = 'lace-teepee-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'Please see the layout options and dimensions needed [here](https://pub-ae783edbdd264f028c01064edee41770.r2.dev/media/Sleepover-Canopy-Layout.pdf). If you are unsure if you have enough space you can provide us with measurements and pictures of the set up area and we can help determine the best layout.', 0 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I don''t have my final guest count yet?', 'We recommend booking for the maximum number of guests that you may have as we can not guarantee that additional items will be available. You have up until 2 weeks before your event (when your final payment is due) to make any changes.', 1 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for indoor sleepover will take place between the hours of 9:00am-4:00pm. Pick ups for all sleepover packages will begin at 10:00am the next day.', 3 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'All hard surfaces are thoroughly disinfected with CDC approved cleaning agents after each use and all linens are professionally laundered.', 4 FROM packages WHERE slug = 'canopy-sleepover';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', 'Small Canopy Lounge- 10ft by 10ft
Large Canopy Lounge- 15ft by 15ft
The Canopy can be slightly adjusted to fit your space. For example the Small Canopy can be set up in a 9''x12'' space if needed. If you are unsure if the set up will fit please reach out and we can help you determine what will work best for your space.', 0 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 1 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for indoor events will begin at 9:00am and go throughout the day. Pick ups for all Lounge Packages will take place the following day, unless otherwise discussed.', 2 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'All hard surfaces are thoroughly disinfected with CDC approved cleaning agents after each use and all linens are professionally laundered.', 3 FROM packages WHERE slug = 'canopy-lounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not service public parks or beaches at this time. Our picnics can be set up indoors or outdoors.', 0 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am (9:00am for indoor events) and go throughout the day. We will schedule delivery based on the event start time provided at the time of booking. The rental period for a picnic is 6 hours, unless paired with one of our Sleepover or Lounges Package. Pick ups for Picnic Packages will vary. Please contact us with any questions. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'celebrations-picnic-adult';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not service public parks or beaches at this time. Our picnics can be set up indoors or outdoors.', 0 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 3 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am (9:00am for indoor events) and go throughout the day. We will schedule delivery based on the event start time provided at the time of booking. The rental period for a picnic is 6 hours, unless paired with one of our Sleepover or Lounges Package. Pick ups for Picnic Packages will vary. Please contact us with any questions. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 4 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'celebrations-picnic-kids';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', '5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.', 0 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'Our MEGATent is waterproof and can be used in the rain. In the event of thunderstorms or high winds it is not safe to use the tent. In the event of inclement weather, you do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am and go throughout the day. We will schedule delivery based on your event start time provided at the time of booking. Delivery may take place the day prior to your event depending on the schedule for that particular date. Pick ups for MEGATent packages will begin the following day, unless otherwise discussed. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'dining-in-the-tent';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Where can I hold my event?', 'Currently, we are only servicing private residences or venues. We do not service public parks or beaches at this time. Our Farm Tables can be set up indoors or outdoors.', 0 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'We highly suggest you have a backup plan for all outdoor events in case of inclement weather. Back up plans can include: Moving your picnic indoors, Set up your picnic under a covered area (provided by the client) such as a covered porch, canopy, pop-up tent, etc., Upgrade your package to one of our Dining in the Tent options (pending availability). You also do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am (9:00am for indoor events) and go throughout the day. We will schedule delivery based on the event start time provided at the time of booking. The rental period for a picnic is 6 hours, unless paired with one of our Sleepover or Lounges Package. Pick ups for Picnic Packages will vary. Please contact us with any questions. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'farm-table-dining';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', '5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.', 0 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'Our MEGATent is waterproof and can be used in the rain. In the event of thunderstorms or high winds it is not safe to use the tent. In the event of inclement weather, you do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 3 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am and go throughout the day. We will schedule delivery based on your event start time provided at the time of booking. Delivery may take place the day prior to your event depending on the schedule for that particular date. Pick ups for all sleepover packages will begin at 10:00am the following day. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 4 FROM packages WHERE slug = 'megaglampout';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How much space is needed?', '5M MEGATent- Requires a 25ft by 25ft grass area for staking (actual tent is 17ft diameter)
6M MEGATent- Requires a 32ft by 32ft grass area for staking (actual tent is 20ft in diameter)
The MEGATent must be set up on a flat grass surface. Non grass surfaces (pavement, stone, turf, sand, etc.) will require sandbags for an additional fee of $150. This must be disclosed at the time of booking.', 0 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'Our MEGATent is waterproof and can be used in the rain. In the event of thunderstorms or high winds it is not safe to use the tent. In the event of inclement weather, you do have the option to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 1 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with a 2 hour delivery and pick up window. Deliveries for outdoor events will begin at 8:00am and go throughout the day. We will schedule delivery based on your event start time provided at the time of booking. Delivery may take place the day prior to your event depending on the schedule for that particular date. Pick ups for MEGATent packages will begin the following day, unless otherwise discussed. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 3 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When will I get my damage deposit back?', 'Your damage deposit will be refunded the Monday after your event as long as all inventory is returned free from any damage.
Damage includes but is not limited to any of the following: stains, broken inventory, missing pieces, and water damage (including damage from tents being left open and items being left out in the rain and/or overnight).
Please note damage deposits are only charged for OUTDOOR events.', 4 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Can I choose my theme/color scheme?', 'Yes! We have several themes/color schemes for you to choose from. We can also put together a custom theme for your event. Additional fees may apply for custom themes. Price varies based on level of customization and size of event. Please contact us for a quote.', 5 FROM packages WHERE slug = 'megalounge';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What happens if it rains?', 'In the event of inclement weather we are happy to reschedule for another date pending availability. You must notify us a minimum of 24 hours before your scheduled delivery window in order to reschedule.', 0 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'When do you set up and pick up?', 'You will receive a confirmation email one week prior to your event with delivery and pick up information. Deliveries for outdoor events will begin at 8:00am and go throughout the day. We will schedule delivery based on your event start time provided at the time of booking. Pick up will take place the same day after your event ends. Picks ups after 11:00pm will be charged an After Hours Pick Up Fee. There are many factors that go into our delivery and pick up schedules including your guest counts, package type, location, weather and our other scheduled events. We may be able to accommodate requests for specific delivery/pick up times if our schedule allows. However, it is not guaranteed. If you need a guaranteed specific delivery and/or pick up time additional fees may apply. Any request must be sent via email no later than 2 weeks before your event.', 1 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you need access to power?', 'Yes, access to power is needed to run the projector. We will provide ample extension cords.', 2 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you provide the movie?', 'While we do not provide the movie we will provide either a DVD/Blue Ray Player or FireStick. You are responsible for providing a DVD/Blue Ray or for streaming a movie through your own account (Netflix, Hulu, etc.). Please note that if you plan to stream a movie there must be a strong internet signal (wifi or data) available at the movie site.', 3 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you stay for the event?', 'We do not stay for the event. We set up everything you need, leave you to enjoy your event and return the next day (or later that day upon request).', 4 FROM packages WHERE slug = 'megamovie-night';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'Do you stay for the event?', 'We do not stay for the event. We set up everything you need, leave you to enjoy your event and return the next day (or later that day upon request).', 0 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What do guests get to keep?', 'Each guest gets to keep their Spa Slippers, Spa Headband, Applicator Brush, and Facial Products (face wipes, face mask, lotion) and Mani/Pedi Products (bath bomb, toe separators, nail file, nail brush). Robes are for event use only, but personalized satin robes can be added as an option for guests to keep.', 1 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'What if I need to cancel?', 'Cancellation 2 Weeks +
If you have to cancel or reschedule your event your 25% deposit may be used as a credit towards a new event within 13 months of your original event date. In addition, you are entitled to a refund of any amount paid above the 25% deposit.
Cancellations within 2 Weeks
If you are canceling your event within 2 weeks, your full payment may be used as a credit towards a new event within 13 months of your original event date.
Cancellations within 24 hours
If you are canceling your event within 24 hours of your scheduled delivery time, your full payment, minus a rescheduling fee, may be used as a credit towards a new event within 13 months of your original event date.', 2 FROM packages WHERE slug = 'pamper-party';
INSERT INTO package_faqs (package_id, question, answer, sort_order) SELECT id, 'How is everything cleaned?', 'All hard surfaces are thoroughly disinfected with CDC approved cleaning agents after each use and all linens are professionally laundered.', 3 FROM packages WHERE slug = 'pamper-party';
